spring:
  jpa:
    database: h2
    database-platform:  org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

fota:
  jpush:
    master-secret: b8eca823a1cf7153088d566b
    app-key: ffaf58e203912a30f8e0cb26
  qiniu:
    access-key: pWojADLRtenEFKascMhlnz8RUkBCDx9ex0oVAPDy
    secret-key: otf8m0AOA1FBi4ukT9qOregQlroE_6-EOr9ML_Ch
    bucket: "allen--test"
    upload-url: http://up-z2.qiniup.com/
    download-url: http://qiniu.hdayun.com/
