spring:
  profiles:
    active: @profile.active@
  application:
    name: @project.artifactId@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  data:
    redis:
      repositories:
        enabled: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  security:
    user:
      name: admin
      password: admin123
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8
fota:
  qiniu:
    return-body: '{"key": $(key),"name": $(fname),"size": $(fsize),"hash": $(etag),"hashType":"etag"}'
    expires: 3600
  jpush:
    upgrade-push-message-content-type: UPGRADE_PUSH
    upgrade-push-message-msg-content: UPGRADE_PUSH
