spring:
  profiles:
    active: @profile.active@
  application:
    name: @project.artifactId@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  data:
    redis:
      repositories:
        enabled: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  security:
    user:
      name: admin
      password: admin123
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8
fota:
  qiniu:
    access-key: pWojADLRtenEFKascMhlnz8RUkBCDx9ex0oVAPDy
    secret-key: otf8m0AOA1FBi4ukT9qOregQlroE_6-EOr9ML_Ch
    bucket: "allen--test"
    upload-url: http://up-z2.qiniup.com/
    download-url: http://q6ancj5hy.bkt.clouddn.com/
    return-body: '{"key": $(key),"name": $(fname),"size": $(fsize),"hash": $(etag),"hashType":"etag"}'
    expires: 3600
  jpush:
    master-secret: b8eca823a1cf7153088d566b
    app-key: ffaf58e203912a30f8e0cb26
    upgrade-push-message-content-type: UPGRADE_PUSH
    upgrade-push-message-msg-content: UPGRADE_PUSH
